<a href="https://colab.research.google.com/github/barajuy2k-cloud/my_first_repo/blob/main/Pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
#pandas practice
import pandas as pd

In [ ]:
!pip3 install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# creating simple data frame

data = {

        "Name" : ["Raju","Rani"],
        "Marks" : [100, 90]
}
df =pd.DataFrame(data)
print(df)

   Name  Marks
0  Raju    100
1  Rani     90

In [ ]:
data = {
    "Name" : ["Raju", "Rani", " Rakumara", "Rakumari"],
    "Marks" : [100, 90, 80, 70]
}
df = pd.DataFrame(data)
print(df)

        Name  Marks
0       Raju    100
1       Rani     90
2   Rakumara     80
3   Rakumari     70

In [ ]:
df =pd.read_excel("/content/Student_Marks1.xlsx")
print(df.head())

   S.No  Admn No.         DOA       Child Name     PEN number         DOB  \
0   NaN       NaN         NaN               NaN           NaN         NaN
1   1.0       2.0           3                 4  5.000000e+00           6
2   1.0    5040.0  10.08.2022    BANTU PRAVEENA  2.069012e+10  24.11.2014
3   2.0    5268.0  18.06.2025  BARNIKANA BALAJI  2.019075e+10  02.07.2015
4   3.0    5280.0  26.06.2025   DONKINA REVATHI  2.087703e+10  15.05.2015

  Gender   Caste    TELUGU Unnamed: 9  ... Unnamed: 22    SOCIAL Unnamed: 24  \
0     NaN    NaN  C.M 20-M  SA-2 80-M  ...    Total 50  C.M 20-M   SA-2 80-M
1       7      8        10         11  ...          24        28          29
2  Female  4-OBC        16         61  ...          85        17          60
3    Male  4-OBC        15         43  ...          65        14          49
4  Female  4-OBC        11         29  ...          52        12          50

  Unnamed: 25  TOTAL Grade WORKING DAYS Attendance Unnamed: 30  \
0   Total 100  MARKS   NaN          NaN       Days           %
1          30     31    32         33.0         34          35
2          77    461    B1        227.0        220     96.9163
3          63    374    B2        227.0        194   85.462555
4          62    326    C1        227.0        198    87.22467

  RESULT / Remarks
0               NaN
1                36
2          PROMOTED
3          PROMOTED
4          PROMOTED

[5 rows x 32 columns]

In [ ]:
df =pd.read_excel("/Student_Marks.xlsx")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318 entries, 0 to 317
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   S.No                 311 non-null    float64
 1   Class                311 non-null    object
 2   Sec                  311 non-null    object
 3   Name                 311 non-null    object
 4   Gender               311 non-null    object
 5   PEN NUMBER           311 non-null    float64
 6   Child ID             310 non-null    float64
 7   Father Name          311 non-null    object
 8   Mother Name          311 non-null    object
 9   Caste                311 non-null    object
 10  CWSN                 311 non-null    object
 11  Type of Impairments  23 non-null     object
 12  AADHAAR No.          311 non-null    object
 13  APAAR ID             264 non-null    object
dtypes: float64(3), object(11)
memory usage: 34.9+ KB

In [ ]:
df =pd.read_excel("/Student_Marks.xlsx")
df["CWSN"]

0       No
1       No
2       No
3       No
4       No
      ...
313     No
314     No
315     No
316    Yes
317     No
Name: CWSN, Length: 318, dtype: object

In [ ]:
df = pd.read_excel("/content/Student_Marks1.xlsx")
df.head()

,S.No,Admn No.,DOA,Child Name,PEN number,DOB,Gender,Caste,TELUGU,Unnamed: 9,...,Unnamed: 22,SOCIAL,Unnamed: 24,Unnamed: 25,TOTAL,Grade,WORKING DAYS,Attendance,Unnamed: 30,RESULT / Remarks
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C.M 20-M,SA-2 80-M,...,Total 50,C.M 20-M,SA-2 80-M,Total 100,MARKS (600),NaN,NaN,Days,%,NaN
1,1.0,2.0,3,4,5.000000e+00,6,7,8,10,11,...,24,28,29,30,31,32,33.0,34,35,36
2,1.0,5040.0,10.08.2022,BANTU PRAVEENA,2.069012e+10,24.11.2014,Female,4-OBC,16,61,...,85,17,60,77,461,B1,227.0,220,96.9163,PROMOTED
3,2.0,5268.0,18.06.2025,BARNIKANA BALAJI,2.019075e+10,02.07.2015,Male,4-OBC,15,43,...,65,14,49,63,374,B2,227.0,194,85.462555,PROMOTED
4,3.0,5280.0,26.06.2025,DONKINA REVATHI,2.087703e+10,15.05.2015,Female,4-OBC,11,29,...,52,12,50,62,326,C1,227.0,198,87.22467,PROMOTED

In [ ]:
df["Child Name "]

0                         NaN
1                           4
2              BANTU PRAVEENA
3            BARNIKANA BALAJI
4             DONKINA REVATHI
5                GANTA SHARAN
6               GANTA SRAVANI
7               GOKADA SARATH
8        JANAPAREDDY TRISANTH
9     KADUTHULA MOHAN KRISHNA
10               KARAKA MOHAN
11         KASAMDASU PADMASRI
12         KOLLIMALLA SARANYA
13              MINDI MOUNIKA
14           PEDIREDLA CHARAN
15         PEDIREDLA JAHANAVI
16          PEDIREDLA LALITHA
17    POTTA PREAM CHAND GANDI
18               SEERA HARSHA
19              SEETHA SWATHI
20           SIRAGAM PRANEETH
21      TUMPALA JYOTHI SWARUP
Name: Child Name , dtype: object

In [ ]:
df["Admn No."]

0        NaN
1        2.0
2     5040.0
3     5268.0
4     5280.0
5     5273.0
6     5027.0
7     5289.0
8     5249.0
9     5271.0
10    5238.0
11    5295.0
12    5291.0
13    5020.0
14    5057.0
15    5042.0
16    5034.0
17    5237.0
18    5276.0
19    5269.0
20    5253.0
21    5259.0
Name: Admn No., dtype: float64

In [ ]:
df.head()

,S.No,Admn No.,DOA,Child Name,PEN number,DOB,Gender,Caste,TELUGU,Unnamed: 9,...,Unnamed: 22,SOCIAL,Unnamed: 24,Unnamed: 25,TOTAL,Grade,WORKING DAYS,Attendance,Unnamed: 30,RESULT / Remarks
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C.M 20-M,SA-2 80-M,...,Total 50,C.M 20-M,SA-2 80-M,Total 100,MARKS (600),NaN,NaN,Days,%,NaN
1,1.0,2.0,3,4,5.000000e+00,6,7,8,10,11,...,24,28,29,30,31,32,33.0,34,35,36
2,1.0,5040.0,10.08.2022,BANTU PRAVEENA,2.069012e+10,24.11.2014,Female,4-OBC,16,61,...,85,17,60,77,461,B1,227.0,220,96.9163,PROMOTED
3,2.0,5268.0,18.06.2025,BARNIKANA BALAJI,2.019075e+10,02.07.2015,Male,4-OBC,15,43,...,65,14,49,63,374,B2,227.0,194,85.462555,PROMOTED
4,3.0,5280.0,26.06.2025,DONKINA REVATHI,2.087703e+10,15.05.2015,Female,4-OBC,11,29,...,52,12,50,62,326,C1,227.0,198,87.22467,PROMOTED

In [ ]:
df.columns

Index(['S.No', 'Admn No.', 'DOA', 'Child Name ', 'PEN number', 'DOB',
       'Gender ', 'Caste', 'TELUGU', 'Unnamed: 9', 'Unnamed: 10', 'HINDI',
       'Unnamed: 12', 'Unnamed: 13', 'ENGLISH', 'Unnamed: 15', 'Unnamed: 16',
       'MATHS ', 'Unnamed: 18', 'Unnamed: 19', 'G.S', 'Unnamed: 21',
       'Unnamed: 22', 'SOCIAL', 'Unnamed: 24', 'Unnamed: 25', 'TOTAL', 'Grade',
       'WORKING DAYS', 'Attendance', 'Unnamed: 30', 'RESULT / Remarks '],
      dtype='object')

In [ ]:
df[["Child Name ", "TOTAL"]]

                Child Name   TOTAL
0                       NaN    NaN
1                         4   31.0
2            BANTU PRAVEENA  461.0
3          BARNIKANA BALAJI  374.0
4           DONKINA REVATHI  326.0
5              GANTA SHARAN  366.0
6             GANTA SRAVANI  322.0
7             GOKADA SARATH  291.0
8      JANAPAREDDY TRISANTH  297.0
9   KADUTHULA MOHAN KRISHNA  267.0
10             KARAKA MOHAN  336.0
11       KASAMDASU PADMASRI  416.0
12       KOLLIMALLA SARANYA  117.0
13            MINDI MOUNIKA  460.0
14         PEDIREDLA CHARAN  495.0
15       PEDIREDLA JAHANAVI  300.0
16        PEDIREDLA LALITHA  449.0
17  POTTA PREAM CHAND GANDI  363.0
18             SEERA HARSHA  426.0
19            SEETHA SWATHI  438.0
20         SIRAGAM PRANEETH  234.0
21    TUMPALA JYOTHI SWARUP  384.0

In [ ]:
df["TOTAL"] = pd.to_numeric(df["TOTAL"], errors='coerce')
max_total = df["TOTAL"].max()
print(max_total)

495.0

In [ ]:
data = {
    "Name" : ["Raju", "Rani", "Rakumara", "Rakumari"],
    "Marks" : [100, 70, 80, 90]
}
df = pd.DataFrame(data)
print(df)

       Name  Marks
0      Raju    100
1      Rani     70
2  Rakumara     80
3  Rakumari     90

In [ ]:
df["Marks"].max()

100

In [ ]:
df["Marks"].min()

70

In [ ]:
df["Marks"].mean()

np.float64(85.0)

In [ ]:
df.sort_values(by="Marks", ascending=False)

       Name  Marks
0      Raju    100
3  Rakumari     90
2  Rakumara     80
1      Rani     70

In [ ]:
data = {
    "Name" : ["Raju", "Rani", " Rakumara", "Rakumari", "Rishi", "Kavya", "Sundari"],
    "Marks" : [100, 90, 34, 70, 20, 45, 70]
}
df = pd.DataFrame(data)
pd.DataFrame(data)
print(df)

        Name  Marks
0       Raju    100
1       Rani     90
2   Rakumara     34
3   Rakumari     70
4      Rishi     20
5      Kavya     45
6    Sundari     70

In [ ]:
#Passed students

df[df["Marks"] >= 35]

       Name  Marks
0      Raju    100
1      Rani     90
3  Rakumari     70
5     Kavya     45
6   Sundari     70

In [ ]:
#2. Failed students
df[df["Marks"] <= 35]

        Name  Marks
2   Rakumara     34
4      Rishi     20

In [ ]:
#3. find top students
df[df["Marks"] >= 90]

   Name  Marks
0  Raju    100
1  Rani     90

In [ ]:
df[df["Marks"] > 90][["Name", "Marks"]]

   Name  Marks
0  Raju    100

In [ ]:
df.sort_values(by="Marks", ascending=False)

        Name  Marks
0       Raju    100
1       Rani     90
3   Rakumari     70
6    Sundari     70
5      Kavya     45
2   Rakumara     34
4      Rishi     20

In [ ]:
df.sort_values(by="Marks", ascending=False).head(5)

       Name  Marks
0      Raju    100
1      Rani     90
3  Rakumari     70
6   Sundari     70
5     Kavya     45

In [ ]:
df[df["Marks"] >= 35]

       Name  Marks
0      Raju    100
1      Rani     90
3  Rakumari     70
5     Kavya     45
6   Sundari     70

In [ ]:
df[df[ "Marks"] <= 35]

        Name  Marks
2   Rakumara     34
4      Rishi     20

In [ ]:
df.sort_values(by="Marks", ascending=False)

        Name  Marks
0       Raju    100
1       Rani     90
3   Rakumari     70
6    Sundari     70
5      Kavya     45
2   Rakumara     34
4      Rishi     20

In [ ]:
df.columns

Index(['Name', 'Marks'], dtype='object')